version: 2.1

#
# This CI configuration heavily relies on templates and CMake. Most of the
# jobs will have the following steps (usually configurable via parameters):
# prepare, build and test.
#
# 'sanity-checks' and 'baselines' are special. The former will run a series
# of checks to see if the patch has the minimum requirements for landing in
# our repository and the latter will generate new baselines for the tests
# in case the PR changes the baselines.
#
workflows:
  version: 2
  development:
    jobs:
      - build-template:
          name: linux-gcc8-release
          executor_name: ubuntu-eoan
          target_is_linux: true
          config_params: '-G Ninja -DCMAKE_INSTALL_PREFIX=/tmp/workspace/install/$CIRCLE_JOB -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8'
          install: true
          metrics: true
          style_tests: true
      - android-unit-test-runner:
          requires:
            - linux-gcc8-release

#
# Executors: we currently support two executors, one based on Ubuntu 19.04 aka Disco
# and another based on macOS + Xcode 11.1.0. The Ubuntu executor is a lot more stable
# and will produce reproduceable builds completely offline because it uses a docker
# image with all the build dependencies preinstalled, whereas the macOS is managed
# by CircleCI and will install dependencies on build time. Build results from the macOS
# bots might differ if in meantime the macOS image gets updated. :-(
#
executors:
  ubuntu-eoan:
    docker:
      # FIXME: Move the image to mbgl/
      - image: tmpsantos/mbgl_ci:1.9
    resource_class: 2xlarge
    working_directory: /src
    environment:
      DISPLAY: :99
      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1:report_error_type=1
      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:halt_on_error=0
      QT_INSTALL_DOCS: /usr/share/qt5/doc
      QT_VERSION: 5
      TSAN_OPTIONS: suppressions=/src/platform/linux/tsan_suppress.txt

commands:
  prepare:
    steps:
      - restore_cache:
          keys:
            - 'ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}'
            - 'ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-'
            - 'ccache-v1-{{ .Environment.CIRCLE_JOB }}-master'
      - run:
          name: Prepare
          command: |
            git submodule sync
            git submodule update --init --recursive
            git gc
            npm install --ignore-scripts
            ulimit -c unlimited
  prepare-linux:
    steps:
      - run:
          name: Prepare Linux
          background: true
          command: |
            Xvfb :99 -noreset -screen 0 1280x1024x24
  prepare-macos:
    steps:
      - run:
          name: Prepare macOS
          command: |
            brew install cmake ccache glfw ninja pkgconfig qt chargepoint/xcparse/xcparse
            brew cask install google-cloud-sdk
            pip install ansi2html scipy
  config:
    parameters:
      config_params:
        type: string
    steps:
      - run:
          name: Configure
          command: |
            cmake . -B build << parameters.config_params >>
  build:
    parameters:
      build_params:
        type: string
    steps:
      - run:
          name: Build
          command: |
            ccache --zero-stats --max-size=2G
            cmake --build build -j $(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null) << parameters.build_params >>
            ccache --show-stats
  install:
    steps:
      - run:
          name: Install
          command: |
            cmake --build build --target install/strip
  test:
    parameters:
      test_params:
        type: string
    steps:
      - run:
          name: Test
          command: |
            cd build
            ctest -V << parameters.test_params >>
  metrics:
    parameters:
      step_name:
        type: string
      metrics_params:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: |
            build/mbgl-render-test-runner << parameters.metrics_params >>
  save:
    steps:
      - save_cache:
          key: 'ccache-v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}'
          paths:
            - .git/modules
            - /Users/distiller/Library/Caches/Homebrew
            - node_modules
            - ~/.ccache
            - ~/.gradle
      - run:
          name: Collecting results
          when: always
          command: |
            mkdir -p /tmp/workspace/metrics && touch /tmp/workspace/.$CIRCLE_JOB
            if [ -d metrics/$CIRCLE_JOB ]; then cp -r metrics/$CIRCLE_JOB /tmp/workspace/metrics; fi
            mkdir -p /tmp/tests/baselines
            if [ -f baselines.patch ]; then cp baselines.patch /tmp/tests/baselines; fi
            mkdir -p /tmp/tests/nitpick
            if [ -f nitpick.patch ]; then cp nitpick.patch /tmp/tests/nitpick; fi
            mkdir -p /tmp/tests/render
            if [ -f clang-tidy.log ]; then cp clang-tidy.log /tmp/tests/clang-tidy; fi
            mkdir -p /tmp/tests/render
            if ls render-test/*.html 1> /dev/null 2>&1; then cp render-test/*.html /tmp/tests/render; fi
            mkdir -p /tmp/tests/metrics
            if ls metrics/*.html 1> /dev/null 2>&1; then cp metrics/*.html /tmp/tests/metrics; fi
            mkdir -p /tmp/tests/coredumps
            if ls core* 1> /dev/null 2>&1; then cp core* /tmp/tests/coredumps; fi
            mkdir -p /tmp/tests/valgrind
            if ls build/Testing/Temporary/MemoryChecker.*.log 1> /dev/null 2>&1; then cp build/Testing/Temporary/MemoryChecker.*.log /tmp/tests/valgrind; fi
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*'
      - store_artifacts:
          path: /tmp/tests
          destination: tests
  login-google-cloud-platform:
    steps:
    - run:
        name: Login Google Cloud Platform
        command: |
          echo "${GCLOUD_SERVICE_ACCOUNT_JSON}" > secret.json
          gcloud auth activate-service-account --key-file secret.json --project android-gl-native
          rm secret.json
  login-google-cloud-platform-ios:
    steps:
    - run:
        name: Login to IOS Google Cloud Platform
        command: |
          if [[ -n "${GCLOUD_SERVICE_ACCOUNT_JSON_IOS}" ]]; then
            echo "${GCLOUD_SERVICE_ACCOUNT_JSON_IOS}" > iosAccount.json
            gcloud auth activate-service-account --key-file iosAccount.json --project ios-mapbox-gl-native
            rm iosAccount.json
          fi
  prepare-ios-codesign-keychain:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Prepare codesign keychain
          command: |
            cd << parameters.directory >>
            fastlane run create_keychain name:fastlane_keychain password:$FASTLANE_PASSWORD timeout:false unlock:true
            fastlane match
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $FASTLANE_PASSWORD fastlane_keychain
  codesign-ios-test-runner:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Codesign iOS TestApp for running on a physical device
          command: |
            cp -r << parameters.directory >>/codesigning build
            cd build
            ./codesigning/generate-entitlements.swift
            ./codesigning/codesign_all.sh
            codesign -dv --verbose=4 Release-iphoneos/*.app # for debugging that app is signed or not
  run-ios-test-app:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Run iOS Test App on Firebase
          no_output_timeout: 30m
          command: |
            if [[ -n "${GCLOUD_SERVICE_ACCOUNT_JSON_IOS}" ]]; then
              # arrange files in a way Firebase expects it, and package them in a zip file
              cp << parameters.directory >>/*_iphoneos13.2-arm64e-release.xctestrun build
              cd build
              zip testapp.zip -r Release-iphoneos/*.app --quiet
              zip testapp.zip *_iphoneos13.2-arm64e-release.xctestrun
              gcloud firebase test ios models list
              gcloud firebase test ios run \
                --test testapp.zip \
                --device model=iphone11,version=13.3,locale=en,orientation=portrait --xcode-version=11.3.1 --timeout 30m \
                --verbosity=debug --no-record-video --results-dir ios-test-app-${CIRCLE_BUILD_NUM}
            fi
  upload-coverage-results:
    steps:
    - run:
        name: Get coverage results
        command: |
          cd build
          find . -type f -iname *.gcda -exec gcov -p -b {} \;
    - run:
        name: Upload coverage results to codecov.io
        command: |
          bash <(curl -sSfL https://codecov.io/bash) -X gcov || echo 'Codecov failed to upload'
  publish-coverage-metrics:
    steps:
    - run:
        name: Upload coverage metrics to s3
        command: |
          if [[ $CIRCLE_BRANCH == master ]]; then
              scripts/publish_core_codecoverage.js -p Linux -s Core
          fi

jobs:
  android-unit-test-runner:
    executor: ubuntu-eoan
    steps:
      - checkout
      - prepare
      - run:
          name: Build UnitTestRunner APK
          command: |
            cd test/android
            ./gradlew --parallel --max-workers=8 -Pmapbox.abis=arm64-v8a app:assembleRelease app:assembleAndroidTest
      - save
  sanity-checks:
    executor: ubuntu-eoan
    steps:
      - checkout
      - prepare
      - config:
          config_params: '-G Ninja -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8'
      - run:
          name: Code Generators
          command: |
            cp build/mbgl-core.license LICENSE.mbgl-core.md
            platform/default/include/mbgl/storage/offline_schema.js
            scripts/generate-shaders.js
            scripts/generate-style-code.js
            git add -A && git diff --staged --exit-code | tee nitpick.patch
      - run:
          name: Validation Scripts
          command: |
            scripts/nitpick/submodule-pin.js
      - run:
          name: CMake Format
          command: |
            cmake-format -i $(find -name '*.cmake'      -and -not -path './vendor/*/*' -and -not -path './build/*')
            cmake-format -i $(find -name CMakeLists.txt -and -not -path './vendor/*/*' -and -not -path './build/*')
            git diff --exit-code | tee nitpick.patch
      - run:
          name: Clang Format
          command: |
            git diff -U0 --ignore-submodules=all --no-color origin/master... *.cpp *.hpp | clang-format-diff-8 -p1 -i
            git diff --exit-code | tee nitpick.patch
      - run:
          name: Clang Tidy
          command: |
            run-clang-tidy-8 -quiet -j $(nproc) -header-filter='.*' -p build $PWD/src/.*cpp $PWD/platform/.*cpp
      - save
  baselines:
    executor: ubuntu-eoan
    steps:
      - checkout
      - prepare
      - prepare-linux
      - attach_workspace:
          at: /tmp/attach
      - run:
          name: 'Binary Size'
          command: |
            /tmp/attach/install/linux-gcc8-release/bin/mbgl-render-test-runner -u rebaseline -p metrics/binary-size.json
      - run:
          name: 'Metrics Baselines'
          command: |
            cp -r /tmp/attach/metrics .
            git add -A && git diff --staged --exit-code | tee baselines.patch
      - save
  build-template:
    parameters:
      config_params:
        type: string
        default: ''
      build_params:
        type: string
        default: ''
      test_params:
        type: string
        default: ''
      executor_name:
        type: string
      target_is_android:
        type: boolean
        default: false
      target_is_linux:
        type: boolean
        default: false
      target_is_macos:
        type: boolean
        default: false
      install:
        type: boolean
        default: false
      metrics:
        type: boolean
        default: false
      style_tests:
        type: boolean
        default: false
      upload_coverage:
        type: boolean
        default: false
      publish_coverage:
        type: boolean
        default: false
    executor: << parameters.executor_name >>
    steps:
      - checkout
      - when:
          condition: << parameters.target_is_android >>
          steps:
            - prepare
            - config:
                config_params: << parameters.config_params >>
            - build:
                build_params: << parameters.build_params >>
      - when:
          condition: << parameters.target_is_linux >>
          steps:
            - prepare
            - prepare-linux
            - config:
                config_params: << parameters.config_params >>
            - build:
                build_params: << parameters.build_params >>
            # - test:
            #     test_params: << parameters.test_params >>
      - when:
          condition: << parameters.target_is_macos >>
          steps:
            - prepare
            - prepare-macos
            - config:
                config_params: << parameters.config_params >>
            - build:
                build_params: << parameters.build_params >>
            - test:
                test_params: << parameters.test_params >>
      - when:
          condition: << parameters.install >>
          steps:
            - install
      # - when:
      #     condition: << parameters.style_tests >>
      #     steps:
      #       - metrics:
      #           step_name: 'Style Tests'
      #           metrics_params: '-u rebaseline -p metrics/$CIRCLE_JOB-style.json'
      - when:
          condition: << parameters.metrics >>
          steps:
            - metrics:
                step_name: 'Metrics'
                metrics_params: '-u rebaseline -p metrics/$CIRCLE_JOB-metrics.json'
      - when:
          condition: << parameters.upload_coverage >>
          steps:
            - upload-coverage-results
      - when:
          condition: << parameters.publish_coverage >>
          steps:
            - publish-coverage-metrics
      - save
